name: hrms
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  get_storage: ^2.1.1
  shared_preferences: ^2.2.2
  dio: ^5.4.0
  intl: ^0.19.0
  path_provider: ^2.1.1
  image_picker: ^1.0.5
  image_cropper: ^5.0.1
  pretty_dio_logger: ^1.3.1
  go_router: ^12.1.3
  flutter_native_splash: ^2.3.8

flutter_native_splash:
  android: true
  color: "#ffffff"
  image: "assets/images/logo_splash.png"
  color_dark: "#ffffff"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700